backend/config/routes.rb
Backend::Application.routes.draw do
  	resources :secret_codes
	resources :roles
	# user and authentication related routes start
	resources :users do
		collection do
			get 'logged_in'
			post 'sign_in' => 'users#user_signin'
			post 'change_password'
			post 'forgot_password'
			get 'resend_confirmation'
			post 'sign_up' => 'users#user_signup'
			get 'sample_user_csv'
			post 'upload_user_csv'
			post 'assign_role'
			delete 'revoke_role'
		end

	end
	devise_for :users, path: 'auth', controllers: {
											 confirmations: 'users/confirmations',
											 passwords: 'users/passwords',
											 registrations: 'users/registrations',
											 sessions: 'users/sessions',
									 }
	#For setting routes devise_scope must be used
	devise_scope :user do
		get 'sign_out' => 'users/sessions#destroy'
		get 'sign_in' => 'users/sessions#new'
		get 'sign_up' => 'users/registrations#new'

	end

	get '/login' => 'home#login'
	# You can have the root of your site routed with "root"
	root 'home#index'
end

backend/app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
	belongs_to :user
	validates :code, :presence => true, :uniqueness => true
end

backend/app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  load_and_authorize_resource
  before_action :set_secret_code, only: [:show, :edit, :update, :destroy]
  before_action :set_form_fields
  # GET /secret_codes
  # GET /secret_codes.json
  def index
    @secret_code = SecretCode.new
    @secret_codes = SecretCode.all
  end

  # GET /secret_codes/1
  # GET /secret_codes/1.json
  def show
  end

  # GET /secret_codes/new
  def new
    @secret_code = SecretCode.new
  end

  # GET /secret_codes/1/edit
  def edit
  end

  # POST /secret_codes
  # POST /secret_codes.json
  def create
    if params[:no_of_codes]
      @nos = (params[:no_of_codes]).to_i
      while @nos > 0
        @secret_code = SecretCode.new
        @secret_code.code = (0...6).map { @lib_for_hash[rand(@lib_for_hash.length)] }.join
        @secret_code.save
        @nos = @nos - 1
      end
      respond_to do |format|
        format.js { render inline: "location.reload()" }
      end
    end
  end

  # PATCH/PUT /secret_codes/1
  # PATCH/PUT /secret_codes/1.json
  def update
    # respond_to do |format|
    #   if @secret_code.update(secret_code_params)
    #     format.html { redirect_to @secret_code, notice: 'Secret code was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @secret_code }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @secret_code.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /secret_codes/1
  # DELETE /secret_codes/1.json
  def destroy
    # @secret_code.destroy
    # respond_to do |format|
    #   format.html { redirect_to secret_codes_url, notice: 'Secret code was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secret_code
      @secret_code = SecretCode.find(params[:id])
    end

    def set_form_fields
      @count = [1, 10, 20, 50, 100]
      @lib_for_hash = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secret_code_params
      # params.require(:secret_code).permit(:code, :user_id)
    end
end

backend/app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

backend/app/views/secret_codes/_form.html.erb
<div id="form-template" class='code-form'>
<%= form_tag(secret_codes_path, method: "post", remote: true) do %>
<div class = 'row'>
    <div class="field col-md-4">
      <div class = 'col-md-6'><%= label_tag(:no_of_code, "No of codes") %></div>
      <div class="check col-md-6"><%= select_tag "no_of_codes", options_for_select(@count,10)%></div>
    </div>
    <div class="actions col-md-2">
      <%= submit_tag("Generate codes", :class => "text btn btn-primary") %>
    </div>
<% end %>
</div>

backend/app/views/secret_codes/edit.html.erb
<h1>Editing Secret Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @secret_code %> |
<%= link_to 'Back', secret_codes_path %>

backend/app/views/secret_codes/index.html.erb
<div class="manage-section">
<% if can? :read, @secret_code %>
<p id="notice"><%= notice %></p>
<% if can? :create, @secret_code %>
<%= render 'form' %>
<% end %>
<h1>Listing Secret Codes(<%= @secret_codes.count rescue 0 %>)</h1>

<div class="manage-section">
  <section class="results">
    <div class="container">
      <% if @secret_codes.present? %>
      <table class="table  table-bordered">
        <thead>
          <tr>
            <th>Code</th>
            <th>User registered</th>
          </tr>
        </thead>

        <tbody>
          <% @secret_codes.each do |secret_code| %>
          <tr>
            <td><%= secret_code.code %></td>
            <td><%= secret_code.user.email rescue nil %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <% end %>
      <% else %>
      <h4><%= "No record found" %></h4>
      <% end %>
    </div>
  </section>
</div>

backend/app/views/secret_codes/new.html.erb
<h1>New Secret Code</h1>

<%= render 'form' %>

<%= link_to 'Back', secret_codes_path %>

backend/app/views/secret_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @secret_code.code %>
</p>

<p>
  <strong>User:</strong>
  <%= @secret_code.user_id %>
</p>

<%= link_to 'Edit', edit_secret_code_path(@secret_code) %> |
<%= link_to 'Back', secret_codes_path %>